version: "3.9"
services:
  db:
    image: postgres:16
    container_name: rmapp-db
    environment:
      POSTGRES_USER: rick
      POSTGRES_PASSWORD: morty
      POSTGRES_DB: rmapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: rmapp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
